### ISSUE TITLE
A problem occurs when running TASSAL

### ISSUE THREAD

**Issue by dreaming0017** [mast-group/tassal#5]
when i input "java -cp tassal/target/tassal-1.1-SNAPSHOT.jar codesum.lm.tui.TrainTopicModel -d E:/SoftwareTest/ExampleProjects/ -w E:/SoftwareTest/ -i 100" in cmd, an error occurs:
At file 0 of 159
Exception in thread "main" java.lang.IllegalStateException: Couldn't create dir:
 E:\SoftwareTest\TopicSum\Source\ActionBarSherlock\E:\SoftwareTest\ExampleProjec
ts\ActionBarSherlock\actionbarsherlock\src\android\support\v4\app
        at codesum.lm.main.CodeUtils.saveFileTokensByNodeID(CodeUtils.java:65)
        at codesum.lm.tui.TrainTopicModel.trainTopicModel(TrainTopicModel.java:85)
        at codesum.lm.tui.TrainTopicModel.main(TrainTopicModel.java:39)

Why?

**Comment by jfowkes** [comment]
This error occurs because TASSAL was written for Linux and assumes Linux file separators and end of line characters throughout. Do you have access to a Linux/Mac machine you could run TASSAL on instead?
